import pandas as pd

#Lecture du fichier
df = pd.read_csv('IDH_par_pays_par_annee.csv', encoding='cp1252')

#Sélection des colonnes intéressantes
# Colonnes d'identification
pays = ['country']
# Colonnes HDI de 2008 à 2023 (2024 n'existe pas encore dans les données)
idh = [f'hdi_{year}' for year in range(2008, 2024)]

#Creer un df sans les colonnes pas intéressantes
df_interessant = df[pays + idh].copy()

#Transformer en format long
df_long = pd.melt(
    df_interessant,
    id_vars=['country'],
    var_name='annee',
    value_name='idh'
)

#Créer une colonne année à partir du nom des colonnes (transformer hdi_year en une colonne hdi avec une valeur pour chaque couple country / year)
df_long['annee'] = df_long['annee'].str.replace('hdi_', '').astype(int)

#Supprimer les lignes sans idh
df_long = df_long.dropna(subset=['idh'])

#Trier par pays et annee (confort visuel)
df_long = df_long.sort_values(['annee', 'annee']).reset_index(drop=True)


#Traduire les noms de pays
countries_en_fr = {
    # --- Nations & territoires ---
    "Afghanistan": "Afghanistan",
    "Albania": "Albanie",
    "Algeria": "Algérie",
    "American Samoa": "Samoa américaines",
    "Andorra": "Andorre",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua-et-Barbuda",
    "Argentina": "Argentine",
    "Armenia": "Arménie",
    "Aruba": "Aruba",
    "Australia": "Australie",
    "Austria": "Autriche",
    "Azerbaijan": "Azerbaïdjan",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahreïn",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbade",
    "Belarus": "Biélorussie",
    "Belgium": "Belgique",
    "Belize": "Belize",
    "Benin": "Bénin",
    "Bermuda": "Bermudes",
    "Bhutan": "Bhoutan",
    "Bolivia Plurinational State of": "Bolivie",
    "Bosnia and Herzegovina": "Bosnie-Herzégovine",
    "Botswana": "Botswana",
    "Brazil": "Brésil",
    "British Virgin Islands": "Îles Vierges britanniques",
    "Brunei Darussalam": "Brunei",
    "Bulgaria": "Bulgarie",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Cambodge",
    "Cameroon": "Cameroun",
    "Canada": "Canada",
    "Cabo Verde": "Cap-Vert",
    "Cayman Islands": "Îles Caïmans",
    "Central African Republic": "République centrafricaine",
    "Chad": "Tchad",
    "Chile": "Chili",
    "China": "Chine",
    "Chinese Taipei": "Taïwan",
    "Colombia": "Colombie",
    "Comoros": "Comores",
    "Congo": "Congo",
    "Cook Islands": "Îles Cook",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatie",
    "Cuba": "Cuba",
    "Cyprus": "Chypre",
    "Czechia": "République tchèque",
    "Denmark": "Danemark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominique",
    "Dominican Republic": "République dominicaine",
    "Ecuador": "Équateur",
    "Egypt": "Égypte",
    "El Salvador": "Salvador",
    "Equatorial Guinea": "Guinée équatoriale",
    "Eritrea": "Érythrée",
    "Estonia": "Estonie",
    "Eswatini Kingdom of": "Eswatini",
    "Ethiopia": "Éthiopie",
    "Fiji": "Fidji",
    "Finland": "Finlande",
    "France": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambie",
    "Georgia": "Géorgie",
    "Germany": "Allemagne",
    "Ghana": "Ghana",
    "United Kingdom": "Royaume-Uni",
    "Greece": "Grèce",
    "Grenada": "Grenade",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guinea": "Guinée",
    "Guinea-Bissau": "Guinée-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haïti",
    "Honduras": "Honduras",
    "Hong Kong, China SAR": "Hong Kong",
    "Hungary": "Hongrie",
    "Iceland": "Islande",
    "India": "Inde",
    "Indonesia": "Indonésie",
    "Iran Islamic Republic of": "Iran",
    "Iraq": "Irak",
    "Ireland": "Irlande",
    "Israel": "Israël",
    "Italy": "Italie",
    "Cte d'Ivoire": "Côte d’Ivoire",
    "Jamaica": "Jamaïque",
    "Japan": "Japon",
    "Jordan": "Jordanie",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Koweït",
    "Kyrgyzstan": "Kirghizistan",
    "Lao People's Democratic Republic": "Laos",
    "Latvia": "Lettonie",
    "Lebanon": "Liban",
    "Lesotho": "Lesotho",
    "Liberia": "Libéria",
    "Libya": "Libye",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituanie",
    "Luxembourg": "Luxembourg",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaisie",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Malta": "Malte",
    "Marshall Islands": "Îles Marshall",
    "Mauritania": "Mauritanie",
    "Mauritius": "Maurice",
    "Mexico": "Mexique",
    "Micronesia Federated States of": "Micronésie",
    "Moldova Republic of": "Moldavie",
    "Monaco": "Monaco",
    "Mongolia": "Mongolie",
    "Montenegro": "Monténégro",
    "Morocco": "Maroc",
    "Mozambique": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namibie",
    "Nauru": "Nauru",
    "Nepal": "Népal",
    "Netherlands": "Pays-Bas",
    "New Zealand": "Nouvelle-Zélande",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigéria",
    "North Korea": "Corée du Nord",
    "North Macedonia": "Macédoine du Nord",
    "Norway": "Norvège",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palau": "Palaos",
    "Palestine, State of": "Palestine",
    "Panama": "Panama",
    "Papua New Guinea": "Papouasie-Nouvelle-Guinée",
    "Paraguay": "Paraguay",
    "Peru": "Pérou",
    "Philippines": "Philippines",
    "Poland": "Pologne",
    "Portugal": "Portugal",
    "Puerto Rico": "Porto Rico",
    "Qatar": "Qatar",
    "Romania": "Roumanie",
    "Russian Federation": "Russie",
    "Rwanda": "Rwanda",
    "Saudi Arabia": "Arabie saoudite",
    "Senegal": "Sénégal",
    "Serbia": "Serbie",
    "Singapore": "Singapour",
    "Slovakia": "Slovaquie",
    "Slovenia": "Slovénie",
    "South Africa": "Afrique du Sud",
    "Korea Republic of": "Corée du Sud",
    "South Sudan": "Soudan du Sud",
    "Spain": "Espagne",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Soudan",
    "Sweden": "Suède",
    "Switzerland": "Suisse",
    "Thailand": "Thaïlande",
    "Tunisia": "Tunisie",
    "Trkiye": "Turquie",
    "Ukraine": "Ukraine",
    "United States": "États-Unis",
    "Uruguay": "Uruguay",
    "Uzbekistan" : "Ouzbékistan",
    "Viet Nam": "Viêt Nam",
    "Zambia": "Zambie",
    "Zimbabwe": "Zimbabwe",
    "Uganda": "Ouganda",
    "Tajikistan": "Tadjikistan",
    "Saint Lucia": "Sainte-Lucie",
    "Hong Kong": "Hong Kong",
    "Venezuela Bolivarian Republic of": "Venezuela",
    "Turkmenistan": "Turkménistan",
    "Syrian Arab Republic": "Syrie",
    "San Marino": "Saint-Marin",
    "United Arab Emirates": "Émirats arabes unis",
    "Trinidad and Tobago": "Trinité-et-Tobago",

    "Macedonia": "Macédoine du Nord",
    "Swaziland": "Eswatini",
    "The Gambia": "Gambie",
    "The Gambie": "Gambie",  
    "Virgin Islands": "Îles Vierges américaines",
    "Federated States of Micronesia": "Micronésie",
    "Republic of the Congo": "Congo",
    "Sao Tome and Principe": "São Tomé-et-Príncipe",
    "Samoa": "Samoa",
    "Tanzania United Republic of": "Tanzanie",
    "Congo Democratic Republic of the": "République démocratique du Congo",
    "Vanuatu": "Vanuatu",
    "Suriname": "Suriname",
    "Togo": "Togo",
    "Timor-Leste": "Timor oriental",
    "Saint Vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
    "Sierra Leone": "Sierra Leone",
    "Tonga": "Tonga",
    "Yemen": "Yémen",
    "Saint Kitts and Nevis": "Saint-Christophe-et-Niévès",
    "Seychelles": "Seychelles",
    "Solomon Islands": "Îles Salomon",
    "Tuvalu": "Tuvalu",
    "Somalia": "Somalie"
}
#Traduction + Suppression des caractères ajoutés après la conversion
df_long["country"] = (
    df_long["country"].str.replace(r"[^A-Za-z ,\-']", "", regex=True).str.strip()
)
df_long["country"] = df_long["country"].map(countries_en_fr)

#Renommer la colonne country en pays
df_long.rename(columns={'country': 'pays'}, inplace=True)

if __name__ == '__main__' :
    df_long.to_pickle("df_idh.pkl")
