import world_bank_data as wb
import pandas as pd

def get_education():
    #Récupérer les dépenses d'éducation
    df = wb.get_series('SE.XPD.TOTL.GD.ZS', 
                   date='2010:2023', 
                   simplify_index=True)

    #Convertir en DataFrame propre
    df_clean = df.reset_index()
    df_clean.columns = ['pays', 'annee', 'education']

    #Convertir les annees en entier
    df_clean['annee'] = df_clean['annee'].astype(int)

    return df_clean

df_clean=get_education()

#Changer les noms de certains pays
country_mapping = {
    # Régions et agrégats (à exclure généralement)
    'Africa Eastern and Southern': 'Afrique orientale et australe',
    'Africa Western and Central': 'Afrique occidentale et centrale',
    'Arab World': 'Monde arabe',
    'Caribbean small states': 'Petits États des Caraïbes',
    'Central Europe and the Baltics': 'Europe centrale et Baltique',
    'Early-demographic dividend': 'Dividende démographique précoce',
    'East Asia & Pacific': 'Asie de l\'Est et Pacifique',
    'East Asia & Pacific (excluding high income)': 'Asie de l\'Est et Pacifique (hors revenu élevé)',
    'East Asia & Pacific (IDA & IBRD countries)': 'Asie de l\'Est et Pacifique (pays IDA et BIRD)',
    'Euro area': 'Zone euro',
    'Europe & Central Asia': 'Europe et Asie centrale',
    'Europe & Central Asia (excluding high income)': 'Europe et Asie centrale (hors revenu élevé)',
    'Europe & Central Asia (IDA & IBRD countries)': 'Europe et Asie centrale (pays IDA et BIRD)',
    'European Union': 'Union européenne',
    'Fragile and conflict affected situations': 'Situations fragiles et touchées par des conflits',
    'Heavily indebted poor countries (HIPC)': 'Pays pauvres très endettés (PPTE)',
    'High income': 'Revenu élevé',
    'IBRD only': 'BIRD uniquement',
    'IDA & IBRD total': 'IDA et BIRD total',
    'IDA blend': 'IDA mixte',
    'IDA only': 'IDA uniquement',
    'IDA total': 'IDA total',
    'Late-demographic dividend': 'Dividende démographique tardif',
    'Latin America & Caribbean': 'Amérique latine et Caraïbes',
    'Latin America & Caribbean (excluding high income)': 'Amérique latine et Caraïbes (hors revenu élevé)',
    'Latin America & the Caribbean (IDA & IBRD countries)': 'Amérique latine et Caraïbes (pays IDA et BIRD)',
    'Least developed countries: UN classification': 'Pays les moins avancés (classification ONU)',
    'Low & middle income': 'Revenu faible et intermédiaire',
    'Low income': 'Revenu faible',
    'Lower middle income': 'Revenu intermédiaire inférieur',
    'Middle East, North Africa, Afghanistan & Pakistan': 'Moyen-Orient, Afrique du Nord, Afghanistan et Pakistan',
    'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)': 'Moyen-Orient, Afrique du Nord, Afghanistan et Pakistan (hors revenu élevé)',
    'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)': 'Moyen-Orient, Afrique du Nord, Afghanistan et Pakistan (IDA et BIRD)',
    'Middle income': 'Revenu intermédiaire',
    'North America': 'Amérique du Nord',
    'Not classified': 'Non classifié',
    'OECD members': 'Membres de l\'OCDE',
    'Other small states': 'Autres petits États',
    'Pacific island small states': 'Petits États insulaires du Pacifique',
    'Post-demographic dividend': 'Post-dividende démographique',
    'Pre-demographic dividend': 'Pré-dividende démographique',
    'Small states': 'Petits États',
    'South Asia': 'Asie du Sud',
    'South Asia (IDA & IBRD)': 'Asie du Sud (IDA et BIRD)',
    'Sub-Saharan Africa': 'Afrique subsaharienne',
    'Sub-Saharan Africa (excluding high income)': 'Afrique subsaharienne (hors revenu élevé)',
    'Sub-Saharan Africa (IDA & IBRD countries)': 'Afrique subsaharienne (pays IDA et BIRD)',
    'Upper middle income': 'Revenu intermédiaire supérieur',
    'World': 'Monde',
    
    # Pays (A-Z)
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albanie',
    'Algeria': 'Algérie',
    'American Samoa': 'Samoa américaines',
    'Andorra': 'Andorre',
    'Angola': 'Angola',
    'Antigua and Barbuda': 'Antigua-et-Barbuda',
    'Argentina': 'Argentine',
    'Armenia': 'Arménie',
    'Aruba': 'Aruba',
    'Australia': 'Australie',
    'Austria': 'Autriche',
    'Azerbaijan': 'Azerbaïdjan',
    'Bahamas, The': 'Bahamas',
    'Bahrain': 'Bahreïn',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbade',
    'Belarus': 'Biélorussie',
    'Belgium': 'Belgique',
    'Belize': 'Belize',
    'Benin': 'Bénin',
    'Bermuda': 'Bermudes',
    'Bhutan': 'Bhoutan',
    'Bolivia': 'Bolivie',
    'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
    'Botswana': 'Botswana',
    'Brazil': 'Brésil',
    'British Virgin Islands': 'Îles Vierges britanniques',
    'Brunei Darussalam': 'Brunei',  # Traduction obligatoire
    'Bulgaria': 'Bulgarie',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cap Vert': 'Cap Vert',  # Traduction obligatoire
    'Cambodia': 'Cambodge',
    'Cameroon': 'Cameroun',
    'Canada': 'Canada',
    'Cayman Islands': 'Îles Caïmans',
    'Central African Republic': 'République centrafricaine',
    'Chad': 'Tchad',
    'Channel Islands': 'Îles Anglo-Normandes',
    'Chile': 'Chili',
    'China': 'Chine',
    'Colombia': 'Colombie',
    'Comoros': 'Comores',
    'Congo, Dem. Rep.': 'République démocratique du Congo',  # Traduction obligatoire
    'Congo, Rep.': 'Congo',  # Traduction obligatoire
    'Costa Rica': 'Costa Rica',
    "Cote d'Ivoire": 'Côte d\'Ivoire',
    'Croatia': 'Croatie',
    'Cuba': 'Cuba',
    'Curacao': 'Curaçao',
    'Cyprus': 'Chypre',
    'Czechia': 'Tchéquie',
    'Denmark': 'Danemark',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominique',
    'Dominican Republic': 'République dominicaine',
    'Ecuador': 'Équateur',
    'Egypt, Arab Rep.': 'Égypte',  # Traduction obligatoire
    'El Salvador': 'Salvador',
    'Equatorial Guinea': 'Guinée équatoriale',
    'Eritrea': 'Érythrée',
    'Estonia': 'Estonie',
    'Eswatini': 'Eswatini',
    'Ethiopia': 'Éthiopie',
    'Faroe Islands': 'Îles Féroé',
    'Fiji': 'Fidji',
    'Finland': 'Finlande',
    'France': 'France',
    'French Polynesia': 'Polynésie française',
    'Gabon': 'Gabon',
    'Gambia, The': 'Gambie',
    'Georgia': 'Géorgie',
    'Germany': 'Allemagne',
    'Ghana': 'Ghana',
    'Gibraltar': 'Gibraltar',
    'Greece': 'Grèce',
    'Greenland': 'Groenland',
    'Grenada': 'Grenade',
    'Guam': 'Guam',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinée',
    'Guinea-Bissau': 'Guinée-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haïti',
    'Honduras': 'Honduras',
    'Hong Kong SAR, China': 'Hong Kong',  # Traduction obligatoire
    'Hungary': 'Hongrie',
    'Iceland': 'Islande',
    'India': 'Inde',
    'Indonesia': 'Indonésie',
    'Iran, Islamic Rep.': 'Iran',  # Traduction obligatoire
    'Irak': 'Irak',  # Traduction obligatoire
    'Ireland': 'Irlande',
    'Isle of Man': 'Île de Man',
    'Israel': 'Israël',
    'Italy': 'Italie',
    'Jamaica': 'Jamaïque',
    'Japan': 'Japon',
    'Jordan': 'Jordanie',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kiribati': 'Kiribati',
    "Korea, Dem. People's Rep.": 'Corée du Nord',  # Traduction obligatoire
    'Korea, Rep.': 'Corée du sud',  # Traduction obligatoire
    'Kosovo': 'Kosovo',
    'Kuwait': 'Koweït',
    'Kyrgyz Republic': 'Kirghizistan',  # Traduction obligatoire
    'Lao PDR': 'Laos',  # Traduction obligatoire
    'Latvia': 'Lettonie',
    'Lebanon': 'Liban',
    'Lesotho': 'Lesotho',
    'Liberia': 'Libéria',
    'Libya': 'Libye',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lituanie',
    'Luxembourg': 'Luxembourg',
    'Macao SAR, China': 'Macao',  # Traduction obligatoire
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaisie',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malte',
    'Marshall Islands': 'Îles Marshall',
    'Mauritania': 'Mauritanie',
    'Mauritius': 'Maurice',
    'Mexico': 'Mexique',
    'Micronesia, Fed. Sts.': 'Micronésie',  # Traduction obligatoire
    'Moldova': 'Moldavie',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolie',
    'Montenegro': 'Monténégro',
    'Morocco': 'Maroc',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibie',
    'Nauru': 'Nauru',
    'Nepal': 'Népal',
    'Netherlands': 'Pays-Bas',
    'New Caledonia': 'Nouvelle-Calédonie',
    'New Zealand': 'Nouvelle-Zélande',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'North Macedonia': 'Macédoine du Nord',
    'Northern Mariana Islands': 'Îles Mariannes du Nord',
    'Norway': 'Norvège',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Palau': 'Palaos',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papouasie-Nouvelle-Guinée',
    'Paraguay': 'Paraguay',
    'Peru': 'Pérou',
    'Philippines': 'Philippines',
    'Poland': 'Pologne',
    'Portugal': 'Portugal',
    'Porto Rico': 'Porto Rico',  # Traduction obligatoire
    'Qatar': 'Qatar',
    'Romania': 'Roumanie',
    'Russian Federation': 'Russie',  # Traduction obligatoire
    'Rwanda': 'Rwanda',
    'Samoa': 'Samoa',
    'San Marino': 'Saint-Marin',
    'Sao Tome and Principe': 'São Tomé-et-Principe',
    'Saudi Arabia': 'Arabie saoudite',
    'Senegal': 'Sénégal',
    'Serbia': 'Serbie',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapour',
    'Sint Maarten (Dutch part)': 'Saint-Martin (partie néerlandaise)',
    'Slovak Republic': 'Slovaquie',  # Traduction obligatoire
    'Slovenia': 'Slovénie',
    'Solomon Islands': 'Îles Salomon',
    'Somalia, Fed. Rep.': 'Somalie',  # Traduction obligatoire
    'South Africa': 'Afrique du Sud',
    'South Sudan': 'Soudan du Sud',
    'Spain': 'Espagne',
    'Sri Lanka': 'Sri Lanka',
    'St. Kitts and Nevis': 'Saint-Christophe-et-Niévès',  # Traduction obligatoire
    'St. Lucia': 'Sainte-Lucie',
    'St. Martin (French part)': 'Saint-Martin (partie française)',
    'St. Vincent and the Grenadines': 'Saint-Vincent-et-les-Grenadines',  # Traduction obligatoire
    'Sudan': 'Soudan',
    'Suriname': 'Suriname',
    'Sweden': 'Suède',
    'Switzerland': 'Suisse',
    'Syrian Arab Republic': 'Syrie',  # Traduction obligatoire
    'Tajikistan': 'Tadjikistan',
    'Tanzania': 'Tanzanie',
    'Thailand': 'Thaïlande',
    'Timor oriental': 'Timor oriental',  # Traduction obligatoire
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinité-et-Tobago',
    'Tunisia': 'Tunisie',
    'Turkiye': 'Turquie',
    'Turkmenistan': 'Turkménistan',
    'Turks and Caicos Islands': 'Îles Turques-et-Caïques',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Ouganda',
    'Ukraine': 'Ukraine',
    'United Arab Emirates': 'Émirats arabes unis',
    'United Kingdom': 'Royaume-Uni',
    'United States': 'États-Unis',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Ouzbékistan',
    'Vanuatu': 'Vanuatu',
    'Venezuela, RB': 'Venezuela',
    'Viêt Nam': 'Viêt Nam',  # Traduction obligatoire
    'Virgin Islands (U.S.)': 'Iles vierges américaines',  # Traduction obligatoire
    'West Bank and Gaza': 'Palestine',  # Traduction obligatoire
    'Yemen, Rep.': 'Yémen',  # Traduction obligatoire
    'Zambia': 'Zambie',
    'Zimbabwe': 'Zimbabwe',
}

df_clean['pays'] = df_clean['pays'].replace(country_mapping)

if __name__ == '__main__' :
    df_clean.to_pickle("df_education.pkl")